### ISSUE TITLE
volumes flag to persist 'parts' folder at `\var\lib\inboxapp` on the sync-engine container

### ISSUE THREAD

**Issue by Analect** [nhurel/nylas-sync-engine#11]
@nhurel 
I was trying to figure out why I couldn't get the `/files/<file_id>/download` endpoint working on a set-up using this dockerized solution.  It seems the problem related to me having upgraded the version of sync-engine a few weeks ago, where according to #4 and the 'Upgrading the engine' part of the README, the suggested approach is to dispose of the old container and run up a new one based on the updated docker image.

As per [this](https://github.com/nylas/sync-engine/issues/398) issue, what I hadn't quite realised was that the sync-engine container retains the file attachments within a folder structure at `/var/lib/inboxapp/parts`, so it seems, in order to persist files between upgrades (and generally to avoid losing attachments if a container gets removed inadvertently), we need to add a `volumes` setting in the sync-engine configuration in the docker-compose.yml, as is in place for the the mysql.  So something like:

```
sync-engine:
  image: nhurel/nylas-sync-engine
  ports:
    - 5555:5555
volumes:
    - nylas_parts:/var/lib/inboxapp
  links:
    - mysql:mysql
    - redis:redis
  hostname: sync-engine
  log_opt:
    max-size: "10m"
    max-file: "10"
```

Do you agree?
If you need me to add it with a pull request, let me know.
